{{ if .Values.bombardier }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombardier
  namespace: {{ .Release.Namespace }}
  labels:
    app: bombardier
    {{ include "backyards-demo.labels" . | nindent 4 }}
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bombardier
  template:
    metadata:
      labels:
        app: bombardier
    spec:
      containers:
      - name: bombardier
        image: alpine/bombardier
        imagePullPolicy: Always
        args:
        - --connections=5
        - --rate=20
        - --duration=100h
        - http://frontpage:8080
      {{- with .Values.resources }}
      resources:
        {{ toYaml . | nindent 12 }}
      {{- end }}
      terminationGracePeriodSeconds: 2
{{ end }}
